name: Run and Upload

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  run-and-upload:
    runs-on: windows-latest
    strategy:
      matrix:
        # Copy from constants.ts
        language:
          [
            'hu',
            'eu',
            'pt',
            'ga',
            'el',
            'de',
            'eo',
            'ar',
            'id',
            'pl',
            'cs',
            'ca',
            'sv',
            'ru',
            'nl',
            'uk',
            # 'en', # too big, crashes the runner
            'ko',
            'es',
            'ja',
            'zh',
            'fr',
            'it',
          ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Make Dictionary for ${{ matrix.language }}
        run: bun run start -l ${{ matrix.language }} -d 2022-12-01

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: out/*.zip
          name: ${{ matrix.language }}

  release:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: run-and-upload
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts to out
        uses: actions/download-artifact@v4
        with:
          path: out

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Generate Release Table
        run: bun run releasetable ${{ github.ref }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}

          draft: false
          prerelease: false
          generate_release_notes: true
          append_body: true
          body_path: release.md
          files: |
            out/*.zip
