name: Run and Upload

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  run-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - run: sudo apt-get install -y bzip2
      - run: bun install --frozen-lockfile
      - run: bun run start -a
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: out/
